### ISSUE TITLE
users.js ფუნქციების ES6 მოდულში გატანა

### ISSUE THREAD

**Issue by beqa-bumbeishvili** [beqa-bumbeishvili/Geolab-JS-React#26]
1. User კლასის სტატიკური ფუნქციების usersHelper მოდულში გატანა (carsHelper მსგავსად)
2. თვითონ User კლასის user.js-ში გატანა (car.js-ს მსგავსად)
3. user-ების მასივის შექმნის usersStore-ში გატანა (carsStore-ს მსგავად)
4. ალერთის ტექსტების alertsHelper-ში გატანა
5. login.html-დან onclick-ების ამოშლა და login.js-ში კლიკების addEventListener-ებით დამატება ( main.js-ის მსგავსად )

**Comment by Ninojakhveladze** [comment]
თუ მჯეროდეს!

**Comment by Ninojakhveladze** [comment]
EZ GG
