### ISSUE TITLE
საიტის შემოწმება

### ISSUE THREAD

**Issue by beqa-bumbeishvili** [beqa-bumbeishvili/Geolab-JS-React#28]
შემოწმება რომ საიტის ყველა ფუნქციონალი გამართულად მუშაობა

**Comment by Ninojakhveladze** [comment]
პატარა ბაგი გვაქ, ლექციაზეც აღნიშნა სოფომ და მერე გავასწოროთ, დადისეიბლებულ ღილაკებზე :D
