### ISSUE TITLE
merge sort გარჩევა - ნინო

### ISSUE THREAD

**Issue by beqa-bumbeishvili** [beqa-bumbeishvili/Geolab-JS-React#29]
მაგალითებით ახსნილი merge sort:
ვიდეო1 - https://www.youtube.com/watch?v=4VqmGXwpLqc
ვიდეო2  - https://www.youtube.com/watch?v=JSceec-wEyw
სტატია - https://medium.com/karuna-sehgal/a-simplified-explanation-of-merge-sort-77089fe03bb2

**Comment by Ninojakhveladze** [comment]
ოუ თენქს, ნეტა აქამდე მენახა ტასკი დეტალურად, ჩავუჯექი ყველა ვიდეოს მგონი და მერე ვნახე ეს ლინკები ;D <3
